openapi: "3.0.3"
info:
  title: webapp API仕様
  version: "1.0.0"
  description: |

    ## OpenAPI

    OpenAPIはjson/yml形式で記述します。基本的にはymlで記述してください。

    OpenAPIのコードは`backend/.docs`以下のディレクトリに格納されます。

    ## モック

    モックサーバーにはPrismを使用します。起動するには**"フロントエンドフォルダで"**以下のコマンドを実行します

    ```
    $ npm run mock-server
    ```

    このポートは4041ポートで起動します。起動には数分かかります。

    ## VSCode拡張

    OpenAPI関連のファイルを編集する際、以下の拡張機能を導入することをお勧めします。

    - [OpenAPI (Swagger) Editor](https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi)
    - [Swagger Viewer](https://marketplace.visualstudio.com/items?itemName=Arjun.swagger-viewer)
    - [Swagger Tools](https://marketplace.visualstudio.com/items?itemName=TheHolyCoder.swagger-tools)

servers:
  - url: http://localhost:4041/
    description: モックサーバー
  - url: http://localhost:8081/
    description: ローカル開発サーバー

paths:
  /.netlify/functions/analysis:
    $ref: "./endpoints/.netlify/functions/analysis.yml"
  /.netlify/functions/getIdByAwayteamAndDate:
    $ref: "./endpoints/.netlify/functions/getIdByAwayteamAndDate.yml"
  /.netlify/functions/getIdByHometeamAndDate:
    $ref: "./endpoints/.netlify/functions/getIdByHometeamAndDate.yml"
  /.netlify/functions/getIdListByDate:
    $ref: "./endpoints/.netlify/functions/getIdListByDate.yml"
  /.netlify/functions/getDetailById:
    $ref: "./endpoints/.netlify/functions/getDetailById.yml"

components:
  schemas:
    # レスポンスオブジェクト
    AnalysisGetResponseObject:
      $ref: "./schemas/responseDataObject/GetAnalysisResponseObject.yml"
    BlankResponseObject:
      $ref: "./schemas/responseDataObject/BlankResponseObject.yml"
    GetGamepkResponseObject:
      $ref: "./schemas/responseDataObject/GetGamepkResponseObject.yml"
    GetGameDetailResponseObject:
      $ref: "./schemas/responseDataObject/GetGameDetailResponseObject.yml"

    # ベースレスポンスオブジェクト
    BaseResponseObject:
      $ref: "./schemas/responseDataObject/base/BaseResponseObject.yml"
    ResultObject:
      $ref: "./schemas/responseDataObject/base/ResultObject.yml"

    # データ
    777486_logistic_regression_analysis_data:
      $ref: "./schemas/data/analysis/777486_logistic_regression_analysis_data.json"
    777504_logistic_regression_analysis_data:
      $ref: "./schemas/data/analysis/777504_logistic_regression_analysis_data.json"
    777509_logistic_regression_analysis_data:
      $ref: "./schemas/data/analysis/777509_logistic_regression_analysis_data.json"
    777537_logistic_regression_analysis_data:
      $ref: "./schemas/data/analysis/777537_logistic_regression_analysis_data.json"
    777600_logistic_regression_analysis_data:
      $ref: "./schemas/data/analysis/777600_logistic_regression_analysis_data.json"
    777630_logistic_regression_analysis_data:
      $ref: "./schemas/data/analysis/777630_logistic_regression_analysis_data.json"
    777640_logistic_regression_analysis_data:
      $ref: "./schemas/data/analysis/777640_logistic_regression_analysis_data.json"

    # others
    settingCommon:
      $ref: "./schemas/SettingCommon.yml"

  responses:
    BlankUnAuthResponse:
      $ref: "./responses/BlankUnAuthResponse.yml"
    AnalysisResponse:
      $ref: "./responses/AnalysisResponse.yml"
    GetIdByAwayteamAndDateResponse:
      $ref: "./responses/GetGamepkResponse.yml"
    GetGameDetailResponse:
      $ref: "./responses/GetGameDetailResponse.yml"
