# get:
#   description: 分析データを取得
#   tags:
#     - 分析データを取得API
#   responses:
#     "200":
#       $ref: "../../../responses/AnalisysResponse.yml"

post:
  description: 分析データを取得
  tags:
    - 分析データを取得API
  requestBody:
    content:
      application/json:
        schema:
          type: array
          items:
            type: string
            description: 試合ID
          example:
            - "2025070101"
            - "2025070102"
            - "2025070103"

  responses:
    "200":
      $ref: "../../../responses/AnalysisResponse.yml"
