# get:
#   description: 分析データを取得
#   tags:
#     - 分析データを取得API
#   responses:
#     "200":
#       $ref: "../../../responses/AnalisysResponse.yml"

get:
  description: 分析データを取得
  tags:
    - 分析データを取得API
  parameters:
    - name: gamepk
      in: query
      required: true
      description: 試合ID

  responses:
    "200":
      $ref: "../../../responses/GetAnalysisResponse.yml"
