get:
  description: 試合IDから詳細を取得
  tags:
    - 詳細取得API
  parameters:
    - name: gamepk
      in: query
      required: true
      description: 試合ID

  responses:
    "200":
      $ref: "../../../responses/GetGameDetailResponse.yml"
