post:
  description: ホームチームと日付から試合IDを取得
  tags:
    - gamepk取得API
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            awayteam:
              type: string
            start_date:
              type: string
            end_date:
              type: string
          required:
            - awayteam
            - start_date
            - end_date
  responses:
    "200":
      $ref: "../../../responses/GetGamepkResponse.yml"
