post:
  description: 日付から試合IDを取得
  tags:
    - gamepk取得API
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            date:
              type: string
          required:
            - date
  responses:
    "200":
      $ref: "../../../responses/GetGamepkResponse.yml"
