get:
  description: 試合IDからムービーデータを取得
  tags:
    - ムービーデータ取得API
  parameters:
    - name: gamepk
      in: query
      required: true
      description: 試合ID

  responses:
    "200":
      $ref: "../../../responses/GetMoviesResponse.yml"
